### PR TITLE
feat: add lcgPerturb and deprecate lcgPertub

### LINKED ISSUE #2: rename lcgPertub to lcgPerturb
From what I've read, I believe the term is `perturb` and not `pertub`.

from Haskell's QuickCheck: https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck-Arbitrary.html#t:CoArbitrary

Also I'm using this library in [`fp-ts-test`](https://github.com/waynevanson/fp-ts-test), so thank you for making this!

### PR DESCRIPTION
**Pull request by waynevanson**
closes #2 

Do you want `lcgPertub` deprecated or removed completely?

### CODE REVIEW

**Review by m-bock — CHANGES_REQUESTED** [review]
Nice. Thank you!
Currently CI does not pass, that's due to a thing that I just changed in master. So please rebase.
I'd also suggest that we don't deprecate but rather just rename. Currently it was only published as "-rc" version.
Plus we don't have so many users yet.

**Comment by waynevanson** [comment]
I've rebased the branch and committed a name change instead of deprecation.

**Comment by m-bock** [comment]
Thanks, I unlocked CI. I think the only thing left is to make it pass (just one fix in the tests). Then I'll release as 1.0.0. And afterwards review the PR in the other repo.

**Comment by waynevanson** [comment]
Renamed!

should #3 and #4 (if any extras) be addressed before v1?

**Comment by m-bock** [comment]
#3 and #4 have high prio, but did not keep me from releasing 1.0.0. They'll go out with 1.1.

**Pull request merged**
